language: generic

os: linux
services: 
  - docker
before_install:
  - docker build -t bcap/docker-react -f Dockerfile.dev .
script:
  - docker run --rm -e CI=true bcap/docker-react npm run test

deploy:
  on:
    branch: master
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-us-east-1-467357729182
  bucket_path: docker-react
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  